name: pubspec_yaml
description: Dart library to access and manipulate content of pubpec.yaml files
version: 2.0.1
homepage: https://github.com/alexei-sintotski/pubspec_yaml

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  collection: ^1.14.0
  functional_data: ^0.3.0
  json2yaml: ^1.0.0
  meta: ^1.1.0
  plain_optional: ^0.1.0
  sum_types: ^0.2.0
  yaml: ^2.2.0

dev_dependencies:
  build_runner: ^1.7.0
  dependency_validator: ^1.4.0
  functional_data_generator: ^0.3.0
  sum_types_generator: ^0.2.0
  test: ^1.9.0
  test_coverage: ^0.4.0
